# Generated by Django 4.2 on 2024-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celularnuevo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='celularnuevo',
            name='nombre',
        ),
    ]
