# Generated by Django 4.2 on 2024-03-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0010_celularnuevo_nombre_alter_celularnuevo_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='celularNuevo',
        ),
    ]
